name: RSS to Cubox (时间戳优化版)
on:
  schedule:
    - cron: "0 8,12,18 * * *"  # 每天执行3次
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 缓存时间戳
        uses: actions/cache@v3
        id: time-cache
        with:
          path: last_run_time.txt
          key: ${{ runner.os }}-timestamp-${{ hashFiles('​**​/rss_sources.txt') }}
          restore-keys: |
            ${{ runner.os }}-timestamp-

      - name: 初始化时间戳
        if: steps.time-cache.outputs.cache-hit != 'true'
        run: |
          echo "1970-01-01 00:00:00" > last_run_time.txt

      - name: 安装依赖
        run: pip install feedparser requests pytz

      - name: 推送新文章
        env:
          CUBOX_API: ${{ secrets.CUBOX_API }}
        run: |
          python3 <<EOF
          import os
          import feedparser
          import requests
          from datetime import datetime, timezone
          import time
          import pytz

          # 读取上次运行时间
          with open('last_run_time.txt', 'r') as f:
              try:
                  last_run_time = datetime.strptime(f.read().strip(), "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
              except ValueError:
                  last_run_time = datetime(1970, 1, 1, tzinfo=timezone.utc)

          current_run_time = datetime.now(timezone.utc)
          
          rss_list = [
              ("https://www.thisiscolossal.com/feed?limit=3", "Art"),
              # ("https://rsshub.app/zhubai/luzhnan?limit=3", "Newsletter"),
              # ("https://rsshub.app/zhubai/other_id?limit=3", "Tech"),
              ("https://daringfireball.net/feeds/json?limit=3", "Tech"),
              ("https://sspai.com/feed?limit=3", "Tech"),
          ]

          processed_entries = set()
          for url, folder in rss_list:
              feed = feedparser.parse(
                  url,
                  response_headers={'content-type': 'text/xml; charset=utf-8'}
              )
              for entry in feed.entries:
                  # 处理多格式时间戳
                  entry_time = datetime.fromtimestamp(
                      time.mktime(entry.published_parsed), 
                      tz=timezone.utc
                  ) if hasattr(entry, 'published_parsed') else last_run_time

                  # 组合唯一标识
                  entry_id = f"{entry.link}-{entry_time.timestamp()}"
                  
                  if (entry_time > last_run_time) and (entry_id not in processed_entries):
                      processed_entries.add(entry_id)
                      
                      payload = {
                          "type": "url",
                          "content": entry.link,
                          "title": entry.title[:100],
                          "folder": folder,
                          "description": entry.description[:500] if hasattr(entry, 'description') else "",
                          "tags": ["自动同步", entry_time.strftime("%Y-%m")]
                      }
                      response = requests.post(
                          os.environ['CUBOX_API'],
                          json=payload,
                          headers={'User-Agent': 'Mozilla/5.0'}
                      )
                      print(f"Status: {response.status_code}, Time: {entry_time.isoformat()}")

          # 写入新时间戳
          with open('last_run_time.txt', 'w') as f:
              f.write(current_run_time.strftime("%Y-%m-%d %H:%M:%S"))
          EOF
